services:
  api:
    build:
      context: ./services/api
    command: uvicorn main:app --host 0.0.0.0 --port 9000
    environment:
      - API_DATA_DIR=/app/data
    volumes:
      - ./data:/app/data
    ports:
      - "9000:9000"
    restart: unless-stopped

  console:
    build:
      context: .
      dockerfile: web/console/Dockerfile
    depends_on:
      - api
    ports:
      - "8080:80"
    restart: unless-stopped
